### ISSUE TITLE
vmagent fails on  Template    Missing: nomad.service(vicky-web)

### ISSUE THREAD

**Issue by flantel** [mr-karan/nomad-monitoring#1]
Hi,
Trying to get this working. However, vmagent always gives the allocation error

 Template    Missing: nomad.service(vicky-web)

If I allow it to run until it fails the error is

Template failed: nomad.service(vicky-web): Get "https://127.0.0.1:4646/v1/service/vicky-web?namespace=default&stale=&wait=60000ms": http: server gave HTTP response to HTTPS client  

My normal NOMAD_ADDR=https://127.0.0.1:4646 so not sure why vmagent is failing.

**Comment by mr-karan** [comment]
This looks like some misconfig with your Nomad cluster and responding with HTTP response on an HTTPS URL.
